# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('relevance_score', models.IntegerField(blank=True, help_text='Relevance score (1-10) assigned by faculty mentor / university review board', null=True)),
                ('mentor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short proposal/project title', max_length=255)),
                ('public_summary', models.TextField(help_text='Public approach + expected outcome. No technical implementation detail. Visible to citizens for feedback.')),
                ('confidential_package', models.TextField(help_text='Technical design, architecture, prototype details, code references. Strictly isolated.')),
                ('submission_hash', models.CharField(blank=True, help_text='SHA-256 hash of confidential package + timestamp generated at submission', max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('merged', 'Merged with Complementary Team')], db_index=True, default='submitted', max_length=30)),
                ('review_feedback', models.TextField(blank=True, help_text='Constructive learning feedback from review board')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestones', models.JSONField(default=list, help_text="Ordered list of milestone dicts: [{'title': str, 'due_date': str, 'completed': bool}]")),
                ('deliverables', models.TextField(blank=True, help_text='Summary of code/hardware/documentation deliverables')),
                ('test_results', models.TextField(blank=True, help_text='Field validation and testing metrics')),
                ('ip_records', models.TextField(blank=True, help_text='Patents, copyright, or tech transfer agreements')),
                ('outcome_status', models.CharField(choices=[('in_progress', 'In Progress'), ('deployed', 'Deployed in Field'), ('abandoned', 'Abandoned')], default='in_progress', max_length=30)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
