# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0002_initial'),
        ('pitches', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfeedback',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_pitch_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitch',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_pitches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitch',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_merged_pitches', to='pitches.pitch'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='student_team',
            field=models.ManyToManyField(help_text='Student collaborators on this pitch', related_name='team_pitches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitch',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_pitches', to='users.university'),
        ),
        migrations.AddField(
            model_name='communityfeedback',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_feedback', to='pitches.pitch'),
        ),
        migrations.AddField(
            model_name='projectlifecycle',
            name='pitch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_lifecycle', to='pitches.pitch'),
        ),
    ]
