# Generated by Django 5.1.15 on 2026-09-13 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfeedback',
            name='is_shared_with_students',
            field=models.BooleanField(default=False, help_text='Mentor decides whether to share this community feedback with the student team'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='submission_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Immutable timestamp at submission for prior-art protection audit trail'),
        ),
    ]
