# Generated by Django 5.1.15 on 2026-09-15 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_status_activityevent_citizenverification_and_more'),
        ('pitches', '0003_communityfeedback_is_shared_with_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='open_call',
            field=models.ForeignKey(blank=True, help_text='Associated university open call if submitted against one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitches', to='issues.opencall'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='version',
            field=models.IntegerField(default=1, help_text='Current solution revision version'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('resubmitted', 'Resubmitted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('merged', 'Merged with Complementary Team')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='PitchVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('public_summary', models.TextField()),
                ('confidential_package', models.TextField()),
                ('submission_hash', models.CharField(blank=True, max_length=64)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitch_version_updates', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='pitches.pitch')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
