# Generated by Django 5.1.15 on 2026-09-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_pitch_open_call_pitch_version_alter_pitch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_feasibility', models.IntegerField(default=0, help_text='Technical Feasibility (0-20)')),
                ('social_impact', models.IntegerField(default=0, help_text='Social Impact (0-20)')),
                ('cost_feasibility', models.IntegerField(default=0, help_text='Cost & Budget (0-15)')),
                ('scalability', models.IntegerField(default=0, help_text='Scalability (0-15)')),
                ('sustainability', models.IntegerField(default=0, help_text='Environmental/Operational Sustainability (0-10)')),
                ('innovation', models.IntegerField(default=0, help_text='Novelty & Innovation (0-10)')),
                ('implementation_readiness', models.IntegerField(default=0, help_text='Implementation Readiness (0-10)')),
                ('total_score', models.IntegerField(default=0, help_text='Calculated sum (0-100)')),
                ('recommendation', models.CharField(choices=[('select', 'Select as Winner'), ('request_changes', 'Request Changes / Revisions'), ('merge', 'Merge with Another Pitch'), ('reject', 'Reject')], default='request_changes', max_length=30)),
                ('comments', models.TextField(blank=True, help_text='Detailed evaluation critique or feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pitches.pitch')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pitch', 'reviewer')},
            },
        ),
    ]
