# Generated by Django 5.1.15 on 2026-09-15 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0005_solutionevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Live demo, deployed prototype, or interactive sandbox URL'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Technical documentation, schema, or architecture whitepaper URL'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='repository_url',
            field=models.URLField(blank=True, help_text='GitHub or GitLab repository URL'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='video_url',
            field=models.URLField(blank=True, help_text='Demo or walkthrough video URL'),
        ),
        migrations.AddField(
            model_name='pitchversionhistory',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pitchversionhistory',
            name='documentation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pitchversionhistory',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pitchversionhistory',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SolutionTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Project Lead / Owner'), ('developer', 'Core Developer / Engineer'), ('designer', 'UI/UX & Hardware Designer'), ('researcher', 'Field & Domain Researcher'), ('other', 'Contributor')], default='developer', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='pitches.pitch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pitch', 'student')},
            },
        ),
    ]
