# Generated by Django 5.1.15 on 2026-09-16 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_acceptance_criteria_discussioncomment'),
        ('pitches', '0006_pitch_demo_url_pitch_documentation_url_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('planning', 'Planning & Architecture Freeze'), ('prototype', 'Prototype Development'), ('pilot', 'Field Pilot Testing'), ('deployment_ready', 'Deployment Ready'), ('deployed', 'Deployed in Field'), ('awaiting_citizen_verification', 'Awaiting Citizen Verification'), ('verified', 'Verified by Citizen'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='planning', max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('deployment_status', models.CharField(blank=True, default='pending', max_length=50)),
                ('deployment_evidence', models.TextField(blank=True, help_text='Deployment verification reports, photos, hardware specs')),
                ('outcome', models.TextField(blank=True, help_text='Final deployment impact and findings')),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='issues.issue')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to=settings.AUTH_USER_MODEL)),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='pitches.pitch')),
                ('team', models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.CharField(blank=True, help_text="Target date or relative timeframe e.g. '30 days'", max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('overdue', 'Overdue')], default='pending', max_length=30)),
                ('evidence', models.TextField(blank=True, help_text='Deliverables link, GitHub commit, documentation, or test results')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True, help_text='Feedback or revision notes from faculty mentor / coordinator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='pitches.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('panelists', models.TextField(blank=True, help_text='Invited panel members, evaluators, or faculty')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Agenda, scoring instructions, or post-session minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sessions', to='issues.issue')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_review_sessions', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sessions', to='pitches.pitch')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='users.university')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
