# Generated by Django 5.1.15 on 2026-09-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_discussioncomment_category_and_more'),
        ('pitches', '0007_project_projectmilestone_reviewsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('student_innovator', 'Student Innovator'), ('faculty_mentor', 'Faculty Mentor'), ('coordinator', 'University Coordinator'), ('industry_partner', 'Industry Innovation Partner')], default='student_innovator', max_length=40)),
                ('title', models.CharField(default='Certificate of Verified Civic Innovation & Field Deployment', max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verification_hash', models.CharField(help_text='Cryptographic SHA-256 seal', max_length=64, unique=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.TextField(blank=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pitches.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pitches.pitch')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('project', 'recipient')},
            },
        ),
    ]
