# Generated by Django 5.1.15 on 2026-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
