# Generated by Django 5.1.15 on 2026-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0009_pitch_public_id_project_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('resubmitted', 'Resubmitted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('merged', 'Merged with Complementary Team'), ('project', 'Active Implementation Project')], db_index=True, default='submitted', max_length=30),
        ),
    ]
