from django.urls import path
from .views import (
    IssueListCreateView,
    IssueDetailView,
    IssueModerationView,
    AdoptIssueView,
    AdminForceAdoptView,
    NominateIssueView,
    ReviewNominationView,
    UniversityNominationsListView,
    CitizenConfirmResolutionView,
    OpenCallListCreateView,
    OpenCallDetailView,
    IssueActivityTimelineView,
    IssueDiscussionListCreateView,
    UniversityActionInboxView,
    IssueStatusHistoryView,
    ChallengeCollaboratorListCreateView,
    ChallengeCollaboratorDetailView,
    StatusContractView,
)

urlpatterns = [
    path('', IssueListCreateView.as_view(), name='issue_list_create'),
    path('status-contract/', StatusContractView.as_view(), name='status_contract'),
    path('action-inbox/', UniversityActionInboxView.as_view(), name='university_action_inbox'),
    path('open-calls/', OpenCallListCreateView.as_view(), name='open_call_list_create'),
    path('open-calls/<int:pk>/', OpenCallDetailView.as_view(), name='open_call_detail'),
    path('nominations/', UniversityNominationsListView.as_view(), name='university_nominations'),
    path('nominations/<int:pk>/review/', ReviewNominationView.as_view(), name='review_nomination'),
    path('<str:pk>/', IssueDetailView.as_view(), name='issue_detail'),
    path('<str:issue_id>/discussions/', IssueDiscussionListCreateView.as_view(), name='issue_discussions'),
    path('<str:issue_id>/collaborators/', ChallengeCollaboratorListCreateView.as_view(), name='issue_collaborators'),
    path('<str:issue_id>/collaborators/<int:pk>/', ChallengeCollaboratorDetailView.as_view(), name='issue_collaborator_detail'),
    path('<str:pk>/moderate/', IssueModerationView.as_view(), name='issue_moderate'),
    path('<str:pk>/adopt/', AdoptIssueView.as_view(), name='issue_adopt'),
    path('<str:pk>/force-adopt/', AdminForceAdoptView.as_view(), name='admin_force_adopt'),
    path('<str:pk>/nominate/', NominateIssueView.as_view(), name='issue_nominate'),
    path('<str:pk>/confirm-resolution/', CitizenConfirmResolutionView.as_view(), name='citizen_confirm_resolution'),
    path('<str:pk>/citizen-confirm-resolution/', CitizenConfirmResolutionView.as_view(), name='citizen_confirm_resolution_alias'),
    path('<str:pk>/citizen-confirm/', CitizenConfirmResolutionView.as_view(), name='citizen_confirm_alias'),
    path('<str:pk>/activity/', IssueActivityTimelineView.as_view(), name='issue_activity_timeline'),
    path('<str:pk>/status-history/', IssueStatusHistoryView.as_view(), name='issue_status_history'),
]
