# Generated by Django 5.1.15 on 2026-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('mentorship', 'Mentorship & Advisory'), ('funding', 'CSR / Grant Funding'), ('prototyping', 'Prototyping & Lab Access'), ('technology_transfer', 'Technology Transfer & Licensing')], default='mentorship', max_length=40)),
                ('initiator', models.CharField(choices=[('university', 'University'), ('industry', 'Industry Partner')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted & MOU Initiated'), ('active', 'Active Collaboration'), ('completed', 'Completed'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('proposal_notes', models.TextField(help_text='Scope of mentorship, funding amount, or prototyping support offered/sought')),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
