# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        ('issues', '0001_initial'),
        ('pitches', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='industryengagement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industryengagement',
            name='industry_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='users.organization'),
        ),
        migrations.AddField(
            model_name='industryengagement',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_engagements', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='industryengagement',
            name='pitch',
            field=models.ForeignKey(blank=True, help_text='Assigned pitch/solution this partnership attaches to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_engagements', to='pitches.pitch'),
        ),
    ]
