# Generated by Django 5.1.15 on 2026-09-16 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_initial'),
        ('pitches', '0007_project_projectmilestone_reviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryengagement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Active implementation project this partnership supports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_engagements', to='pitches.project'),
        ),
    ]
