# Generated by Django 5.1.15 on 2026-09-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0003_industryengagement_project"),
        ("pitches", "0011_mentorassignment_projectdeliverable_solutionteam_and_more"),
        ("users", "0002_auditlog_facultyprofile_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Funding amount in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("csr_grant", "CSR Grant"),
                            ("govt_scheme", "Government Innovation Scheme"),
                            ("equity", "Incubation Equity / Seed"),
                            ("prize", "Competition / Hackathon Prize"),
                        ],
                        default="csr_grant",
                        max_length=30,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="Purpose of grant / funding terms"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Funding Proposed"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_grants",
                        to="users.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_grants",
                        to="pitches.project",
                    ),
                ),
            ],
        ),
    ]
