# Generated by Django 5.1.15 on 2026-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('self_adopted', 'University Self-Adopted'), ('nomination_approved', 'Student Nomination Approved')], default='self_adopted', max_length=30)),
                ('adopted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the problem')),
                ('expected_outcome', models.TextField(help_text='Expected social impact or desired solution')),
                ('photo', models.ImageField(blank=True, help_text='Mandatory photographic evidence', null=True, upload_to='issues/photos/')),
                ('photo_url', models.URLField(blank=True, help_text='Alternative web link or cloud storage URL')),
                ('documents', models.FileField(blank=True, null=True, upload_to='issues/docs/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('agriculture', 'Agriculture'), ('water', 'Water & Sanitation'), ('environment', 'Environment & Forests'), ('energy', 'Renewable Energy'), ('urban_infra', 'Urban Infrastructure'), ('accessibility', 'Accessibility & Inclusion'), ('public_admin', 'Public Administration'), ('rural_livelihoods', 'Rural Livelihoods'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('ai_confidence', models.FloatField(default=0.0, help_text='Confidence score from AI categorization')),
                ('ai_triage_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('validated', 'Validated & Published'), ('adopted', 'Adopted by University'), ('assigned', 'Team Assigned'), ('resolved', 'Resolved & Tracked')], db_index=True, default='submitted', max_length=30)),
                ('is_escalated', models.BooleanField(default=False, help_text='Auto-escalated if unadopted past window')),
                ('citizen_verified_resolved', models.BooleanField(blank=True, null=True)),
                ('citizen_feedback_on_resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True, help_text='Why the student believes their university should solve this')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (Adoption Created)'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
