# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='nominated_by',
            field=models.ForeignKey(blank=True, help_text='Student who initiated the nomination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoption',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_issues', to='users.university'),
        ),
        migrations.AddField(
            model_name='issue',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Reference to original issue if marked as duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoption',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='studentnomination',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_nominations', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='studentnomination',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_nominations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentnomination',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nominations', to='users.university'),
        ),
        migrations.AlterUniqueTogether(
            name='studentnomination',
            unique_together={('issue', 'university', 'student')},
        ),
    ]
