# Generated by Django 5.1.15 on 2026-09-15 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='University coordinator who approved or adopted this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_adoptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('requested', 'Requested'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('validating', 'Under Moderation'), ('validated', 'Validated & Published'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('adopted', 'Adopted by University'), ('assigned', 'Team Assigned'), ('resolved', 'Resolved & Tracked'), ('reopened', 'Reopened')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='IssueStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_status_changes', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
