# Generated by Django 5.1.15 on 2026-09-15 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_adoption_coordinator_adoption_status_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('validating', 'Under Moderation'), ('validated', 'Validated & Published'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('adopted', 'Adopted by University'), ('assigned', 'Team Assigned'), ('deployed', 'Deployed in Field'), ('awaiting_verification', 'Awaiting Citizen Verification'), ('resolved', 'Resolved & Tracked'), ('reopened', 'Reopened')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_timeline', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('verified', 'Verified Resolved'), ('not_resolved', 'Not Resolved')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_verifications', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='OpenCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True)),
                ('departments', models.CharField(blank=True, max_length=255)),
                ('funding', models.CharField(blank=True, max_length=100)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('max_teams', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_open_calls', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_calls', to='issues.issue')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_calls', to='users.university')),
            ],
        ),
    ]
