# Generated by Django 5.1.15 on 2026-09-15 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_status_activityevent_citizenverification_and_more'),
        ('pitches', '0006_pitch_demo_url_pitch_documentation_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='acceptance_criteria',
            field=models.TextField(blank=True, help_text='Requirements, target metrics, and acceptance criteria'),
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('challenge', 'Challenge Discussion'), ('solution', 'Solution Technical Discussion')], default='challenge', max_length=20)),
                ('content', models.TextField(help_text='Discussion message, technical comment, or requirement inquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='issues.issue')),
                ('pitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='pitches.pitch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
