# Generated by Django 5.1.15 on 2026-09-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_acceptance_criteria_discussioncomment'),
        ('pitches', '0007_project_projectmilestone_reviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenverification',
            name='photo_video_url',
            field=models.URLField(blank=True, help_text='Photo or video URL evidencing unresolved condition', max_length=500),
        ),
        migrations.AddField(
            model_name='citizenverification',
            name='what_is_still_wrong',
            field=models.TextField(blank=True, help_text='Detailed explanation of what remains unresolved'),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='pitches.project'),
        ),
        migrations.AlterField(
            model_name='citizenverification',
            name='evidence',
            field=models.TextField(blank=True, help_text='Links, test readings, or proof'),
        ),
        migrations.AlterField(
            model_name='citizenverification',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for verdict'),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='target_type',
            field=models.CharField(choices=[('challenge', 'Challenge Discussion'), ('solution', 'Solution Technical Discussion'), ('project', 'Project Technical Discussion')], default='challenge', max_length=20),
        ),
    ]
