# Generated by Django 5.1.15 on 2026-09-16 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_citizenverification_photo_video_url_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='category',
            field=models.CharField(default='general', help_text='Discussion topic category (Issue 41: clarification, context, requirements, constraints, evidence, technical, review, implementation, changes, mentorship, general)', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='maintaining_university',
            field=models.ForeignKey(blank=True, help_text='University currently maintaining this challenge repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_issues', to='users.university'),
        ),
        migrations.AddField(
            model_name='issue',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='University coordinator who actively manages this repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Authority/moderator who validated and approved this challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChallengeCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('maintainer', 'Maintainer'), ('coordinator', 'University Coordinator'), ('faculty', 'Faculty Mentor'), ('student_contributor', 'Student Contributor'), ('government', 'Government Authority'), ('industry_partner', 'Industry Partner'), ('citizen_contributor', 'Citizen Contributor')], default='citizen_contributor', max_length=30)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom collaborator permissions/capabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators_added', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='issues.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('issue', 'user')},
            },
        ),
    ]
