# Generated by Django 5.1.15 on 2026-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_discussioncomment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when adoption was approved by coordinator', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='constraints',
            field=models.TextField(blank=True, help_text='Technical, legal, operational or geographic constraints'),
        ),
        migrations.AddField(
            model_name='issue',
            name='context',
            field=models.TextField(blank=True, help_text='Background context for the challenge'),
        ),
        migrations.AddField(
            model_name='issue',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='requirements',
            field=models.TextField(blank=True, help_text='Functional and domain requirements'),
        ),
    ]
