# Generated by Django 5.1.15 on 2026-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_adoption_approved_at_issue_constraints_issue_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('validating', 'Under Moderation'), ('validated', 'Validated & Published'), ('available_for_adoption', 'Available for Adoption'), ('adoption_requested', 'Adoption Requested'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('adopted', 'Adopted by University'), ('open', 'Open for Solutions'), ('under_review', 'Solutions Under Review'), ('solution_selected', 'Solution Selected'), ('assigned', 'Team Assigned'), ('project', 'Implementation Project Active'), ('prototype', 'Prototype in Development'), ('pilot', 'Pilot Testing in Field'), ('deployed', 'Deployed in Field'), ('awaiting_citizen_verification', 'Awaiting Citizen Verification'), ('awaiting_verification', 'Awaiting Citizen Verification (Alias)'), ('verified', 'Verified by Citizen'), ('failed', 'Verification Failed'), ('resolved', 'Resolved & Tracked'), ('reopened', 'Reopened')], db_index=True, default='submitted', max_length=30),
        ),
    ]
