# Generated by Django 5.1.15 on 2026-09-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_alter_issue_status"),
        ("pitches", "0011_mentorassignment_projectdeliverable_solutionteam_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployment_location", models.CharField(max_length=255)),
                ("deployment_date", models.DateField(blank=True, null=True)),
                ("version_deployed", models.CharField(default="v1.0", max_length=50)),
                (
                    "deployment_status",
                    models.CharField(
                        choices=[
                            ("planned", "Deployment Planned"),
                            ("in_progress", "Field Deployment Active"),
                            ("completed", "Deployment Completed"),
                            ("failed", "Deployment Failed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Links to test reports, photo/video evidence, telemetry",
                    ),
                ),
                (
                    "impact_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Measured outcome metrics e.g. beneficiaries, efficiency score",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_deployments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="pitches.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="issues/media/"),
                ),
                ("file_url", models.URLField(blank=True, max_length=500)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image Photo"),
                            ("video", "Video Evidence"),
                            ("document", "Document Report"),
                            ("evidence", "Field Test Evidence"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="issues.issue",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_issue_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution_summary",
                    models.TextField(
                        help_text="Summary of how the societal challenge was solved"
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="Final field outcome and measurable social impact",
                    ),
                ),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Verification links, documents or test readings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_record",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions",
                        to="pitches.project",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(default="AI_SIMILARITY", max_length=50),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suspected", "Suspected Duplicate"),
                            ("confirmed", "Confirmed Duplicate"),
                            ("rejected", "Not Duplicate"),
                        ],
                        default="suspected",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_duplicates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_targets",
                        to="issues.issue",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_sources",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "unique_together": {("issue", "duplicate_issue")},
            },
        ),
    ]
