# Generated by Django 5.1.15 on 2026-09-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Logical notification identity / event identifier to prevent duplicate notifications (Issue 53)', max_length=255, null=True),
        ),
    ]
